# Generated by Django 5.2.3 on 2025-06-28 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
