# Generated by Django 5.2.3 on 2025-06-28 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dias_semanales',
            field=models.ManyToManyField(related_name='servicios', to='services.diasemanal'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicios', to=settings.AUTH_USER_MODEL),
        ),
    ]
