# Generated by Django 5.2.3 on 2025-06-28 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='dias_disponibles',
            field=models.ManyToManyField(related_name='cuidadores', to='services.diasemanal'),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuidadores', to='services.horariodiario'),
        ),
    ]
