# Generated by Django 5.2.3 on 2025-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_certificacion_dias_disponibles_certificacion_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
