# Generated by Django 5.2.3 on 2025-08-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_calificacion_delete_clasificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificacion',
            old_name='nommbre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='dias_disponibles',
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='horario',
        ),
    ]
