# Generated by Django 5.2.3 on 2025-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_nommbre_certificacion_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='reportada',
            field=models.BooleanField(default=False),
        ),
    ]
